### ISSUE TITLE
Unable to Connect to GPRS

### ISSUE THREAD

**Issue by emil01** [sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library#1]
While running the phant_example, when trying to connect to GPRS it kept returning error code -2. 
Fixed it by adding at line 41 of **MG2639_GPRS.cpp**

```
cell.sendATCommand("+ZPNUM=\"<APN Name>\",\"<user_name>\",\"<password>\"");
```

It would be better if we could add a new function to set the APN in such cases. Let me know if you need me to go ahead and add the function. 

thanks
emil varughese

**Comment by suprnrdy** [comment]
This should be added, or noted in the Source code.

**Comment by bboyho** [comment]
Hi,

Unfortunately, the product has been retired from our catalog.  Additionally, Phant is no longer in service. There are no plans to update the library.
