### ISSUE TITLE
Please make a release to get the updated category displayed in the Arduino Library Manager

### ISSUE THREAD

**Issue by 00alis** [sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library#3]
Hi!
On https://create.arduino.cc/editor (the Arduino Web IDE) we include all the libraries in the Library Manager, your library is giving a warning for every single compilation, and many users have complained about it on our Forum.
`WARNING: Category '' in library parkFun MG2639 CellShield is not valid. Setting to 'Uncategorized'`

This is due to the fact that you have modified the library.properties but haven't published a release yet.

We would really appreciate if you could make a release, so that the updated version will be automatically displayed in the Library Manager and the warning will disappear.

Thanks a lot!

**Comment by ToniCorinne** [comment]
Hi @00alis - thanks for the catch on that! The tag has been updated. Please let us know if it's still causing grief. 

Thanks!
